# Generated by Django 5.1.7 on 2025-03-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
